feat: Set the API URL.
The API URL is our Fly.io app for `primer-service`.

Ref:

https://vitejs.dev/guide/env-and-mode.html
https://orval.dev/guides/set-base-url

Note: despite what https://vitejs.dev/guide/env-and-mode.html says
about "using the full static string" for environment variables like
`import.meta.env.VITE_API_URL`, I could not get that to work, as the
build reported the following error:

```
src/primer-api/mutator/use-custom-instance.ts(3,71): error TS4111: Property 'VITE_API_URL' comes from an index signature, so it must be accessed with ['VITE_API_URL']
```

Therefore, we use dynamic key access, which appears to work, based on
the output generated by the production build.